package com.xTNL.entities;
// Generated Nov 17, 2018 10:54:28 PM by Hibernate Tools 5.0.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Chitietdathang generated by hbm2java
 */
@Entity
@Table(name = "chitietdathang", catalog = "duan2")
public class Chitietdathang implements java.io.Serializable {

	private Integer idChiTietDatHang;
	private Chitietsp chitietsp;
	private Dathang dathang;
	private int soLuong;

	public Chitietdathang() {
	}

	public Chitietdathang(Chitietsp chitietsp, Dathang dathang, int soLuong) {
		this.chitietsp = chitietsp;
		this.dathang = dathang;
		this.soLuong = soLuong;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "IdChiTietDatHang", unique = true, nullable = false)
	public Integer getIdChiTietDatHang() {
		return this.idChiTietDatHang;
	}

	public void setIdChiTietDatHang(Integer idChiTietDatHang) {
		this.idChiTietDatHang = idChiTietDatHang;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdChiTietSP", nullable = false)
	public Chitietsp getChitietsp() {
		return this.chitietsp;
	}

	public void setChitietsp(Chitietsp chitietsp) {
		this.chitietsp = chitietsp;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdDatHang", nullable = false)
	public Dathang getDathang() {
		return this.dathang;
	}

	public void setDathang(Dathang dathang) {
		this.dathang = dathang;
	}

	@Column(name = "SoLuong", nullable = false)
	public int getSoLuong() {
		return this.soLuong;
	}

	public void setSoLuong(int soLuong) {
		this.soLuong = soLuong;
	}

}
