package com.xTNL.entities;
// Generated Nov 17, 2018 10:54:28 PM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Danhmucsp generated by hbm2java
 */
@Entity
@Table(name = "danhmucsp", catalog = "duan2")
public class Danhmucsp implements java.io.Serializable {

	private Integer idDanhMucSp;
	private String name;
	private Date thoiGianTao;
	private Date thoiGianSua;
	private int sortId;
	private Set<Danhmucsp2> danhmucsp2s = new HashSet<Danhmucsp2>(0);
	private Set<Chitietsp> chitietsps = new HashSet<Chitietsp>(0);

	public Danhmucsp() {
	}

	public Danhmucsp(String name, Date thoiGianTao, int sortId) {
		this.name = name;
		this.thoiGianTao = thoiGianTao;
		this.sortId = sortId;
	}

	public Danhmucsp(String name, Date thoiGianTao, Date thoiGianSua, int sortId, Set<Danhmucsp2> danhmucsp2s,
			Set<Chitietsp> chitietsps) {
		this.name = name;
		this.thoiGianTao = thoiGianTao;
		this.thoiGianSua = thoiGianSua;
		this.sortId = sortId;
		this.danhmucsp2s = danhmucsp2s;
		this.chitietsps = chitietsps;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "IdDanhMucSP", unique = true, nullable = false)
	public Integer getIdDanhMucSp() {
		return this.idDanhMucSp;
	}

	public void setIdDanhMucSp(Integer idDanhMucSp) {
		this.idDanhMucSp = idDanhMucSp;
	}

	@Column(name = "Name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ThoiGianTao", nullable = false, length = 19)
	public Date getThoiGianTao() {
		return this.thoiGianTao;
	}

	public void setThoiGianTao(Date thoiGianTao) {
		this.thoiGianTao = thoiGianTao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ThoiGianSua", length = 19)
	public Date getThoiGianSua() {
		return this.thoiGianSua;
	}

	public void setThoiGianSua(Date thoiGianSua) {
		this.thoiGianSua = thoiGianSua;
	}

	@Column(name = "sortId", nullable = false)
	public int getSortId() {
		return this.sortId;
	}

	public void setSortId(int sortId) {
		this.sortId = sortId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "danhmucsp",cascade = CascadeType.ALL)
	public Set<Danhmucsp2> getDanhmucsp2s() {
		return this.danhmucsp2s;
	}

	public void setDanhmucsp2s(Set<Danhmucsp2> danhmucsp2s) {
		this.danhmucsp2s = danhmucsp2s;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "danhmucsp",cascade = CascadeType.ALL)
	public Set<Chitietsp> getChitietsps() {
		return this.chitietsps;
	}

	public void setChitietsps(Set<Chitietsp> chitietsps) {
		this.chitietsps = chitietsps;
	}

}
