package com.xTNL.entities;
// Generated Nov 17, 2018 10:54:28 PM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Danhmucsp2 generated by hbm2java
 */
@Entity
@Table(name = "danhmucsp2", catalog = "duan2")
public class Danhmucsp2 implements java.io.Serializable {

	private Integer idDanhMucSp2;
	private Danhmucsp danhmucsp;
	private String name;
	private Date thoiGianTao;
	private Date thoiGianSua;
	private int sortId;

	public Danhmucsp2() {
	}

	public Danhmucsp2(Danhmucsp danhmucsp, String name, Date thoiGianTao, int sortId) {
		this.danhmucsp = danhmucsp;
		this.name = name;
		this.thoiGianTao = thoiGianTao;
		this.sortId = sortId;
	}

	public Danhmucsp2(Danhmucsp danhmucsp, String name, Date thoiGianTao, Date thoiGianSua, int sortId) {
		this.danhmucsp = danhmucsp;
		this.name = name;
		this.thoiGianTao = thoiGianTao;
		this.thoiGianSua = thoiGianSua;
		this.sortId = sortId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "IdDanhMucSP2", unique = true, nullable = false)
	public Integer getIdDanhMucSp2() {
		return this.idDanhMucSp2;
	}

	public void setIdDanhMucSp2(Integer idDanhMucSp2) {
		this.idDanhMucSp2 = idDanhMucSp2;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdDanhMucSP", nullable = false)
	public Danhmucsp getDanhmucsp() {
		return this.danhmucsp;
	}

	public void setDanhmucsp(Danhmucsp danhmucsp) {
		this.danhmucsp = danhmucsp;
	}

	@Column(name = "Name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ThoiGianTao", nullable = false, length = 19)
	public Date getThoiGianTao() {
		return this.thoiGianTao;
	}

	public void setThoiGianTao(Date thoiGianTao) {
		this.thoiGianTao = thoiGianTao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ThoiGianSua", length = 19)
	public Date getThoiGianSua() {
		return this.thoiGianSua;
	}

	public void setThoiGianSua(Date thoiGianSua) {
		this.thoiGianSua = thoiGianSua;
	}

	@Column(name = "sortId", nullable = false)
	public int getSortId() {
		return this.sortId;
	}

	public void setSortId(int sortId) {
		this.sortId = sortId;
	}

}
