package com.xTNL.entities;
// Generated Nov 17, 2018 10:54:28 PM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Gallery generated by hbm2java
 */
@Entity
@Table(name = "gallery", catalog = "duan2")
public class Gallery implements java.io.Serializable {

	private Integer idGallery;
	private Chitietsp chitietsp;
	private Date thoiGianTao;
	private String images;

	public Gallery() {
	}

	public Gallery(Chitietsp chitietsp, Date thoiGianTao, String images) {
		this.chitietsp = chitietsp;
		this.thoiGianTao = thoiGianTao;
		this.images = images;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "IdGallery", unique = true, nullable = false)
	public Integer getIdGallery() {
		return this.idGallery;
	}

	public void setIdGallery(Integer idGallery) {
		this.idGallery = idGallery;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdChiTietSP", nullable = false)
	public Chitietsp getChitietsp() {
		return this.chitietsp;
	}

	public void setChitietsp(Chitietsp chitietsp) {
		this.chitietsp = chitietsp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ThoiGianTao", nullable = false, length = 19)
	public Date getThoiGianTao() {
		return this.thoiGianTao;
	}

	public void setThoiGianTao(Date thoiGianTao) {
		this.thoiGianTao = thoiGianTao;
	}

	@Column(name = "Images", nullable = false)
	public String getImages() {
		return this.images;
	}

	public void setImages(String images) {
		this.images = images;
	}

}
