package com.xTNL.entities;
// Generated Nov 17, 2018 10:54:28 PM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Hieusp generated by hbm2java
 */
@Entity
@Table(name = "hieusp", catalog = "duan2", uniqueConstraints = @UniqueConstraint(columnNames = "sortId"))
public class Hieusp implements java.io.Serializable {

	private Integer idHieuSp;
	private String tenHieuSp;
	private Date thoiGianTao;
	private Date thoiGianSua;
	private int sortId;
	private String moTaThem;
	private Set<Chitietsp> chitietsps = new HashSet<Chitietsp>(0);

	public Hieusp() {
	}

	public Hieusp(String tenHieuSp, Date thoiGianTao, int sortId) {
		this.tenHieuSp = tenHieuSp;
		this.thoiGianTao = thoiGianTao;
		this.sortId = sortId;
	}

	public Hieusp(String tenHieuSp, Date thoiGianTao, Date thoiGianSua, int sortId, String moTaThem,
			Set<Chitietsp> chitietsps) {
		this.tenHieuSp = tenHieuSp;
		this.thoiGianTao = thoiGianTao;
		this.thoiGianSua = thoiGianSua;
		this.sortId = sortId;
		this.moTaThem = moTaThem;
		this.chitietsps = chitietsps;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "IdHieuSP", unique = true, nullable = false)
	public Integer getIdHieuSp() {
		return this.idHieuSp;
	}

	public void setIdHieuSp(Integer idHieuSp) {
		this.idHieuSp = idHieuSp;
	}

	@Column(name = "TenHieuSP", nullable = false)
	public String getTenHieuSp() {
		return this.tenHieuSp;
	}

	public void setTenHieuSp(String tenHieuSp) {
		this.tenHieuSp = tenHieuSp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ThoiGianTao", nullable = false, length = 19)
	public Date getThoiGianTao() {
		return this.thoiGianTao;
	}

	public void setThoiGianTao(Date thoiGianTao) {
		this.thoiGianTao = thoiGianTao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ThoiGianSua", length = 19)
	public Date getThoiGianSua() {
		return this.thoiGianSua;
	}

	public void setThoiGianSua(Date thoiGianSua) {
		this.thoiGianSua = thoiGianSua;
	}

	@Column(name = "sortId", unique = true, nullable = false)
	public int getSortId() {
		return this.sortId;
	}

	public void setSortId(int sortId) {
		this.sortId = sortId;
	}

	@Column(name = "MoTaThem")
	public String getMoTaThem() {
		return this.moTaThem;
	}

	public void setMoTaThem(String moTaThem) {
		this.moTaThem = moTaThem;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hieusp",cascade = CascadeType.ALL)
	public Set<Chitietsp> getChitietsps() {
		return this.chitietsps;
	}

	public void setChitietsps(Set<Chitietsp> chitietsps) {
		this.chitietsps = chitietsps;
	}

}
