package com.xTNL.entities;
// Generated Nov 17, 2018 10:54:28 PM by Hibernate Tools 5.0.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users", catalog = "duan2", uniqueConstraints = @UniqueConstraint(columnNames = "Username"))
public class Users implements java.io.Serializable {

	private Integer idUsername;
	private String username;
	private String password;
	private String password2;
	private String email;
	private String hoTen;
	private int gioiTinh;
	private double sdtUser1;
	private Double sdtUser2;
	private String diaChi;
	private Date thoiGianTao;
	private Date thoiGianSua;
	private Date thoiGianXoa;
	private String role;
	private String status;
	private String moTaThem;
	private Set<Dathang> dathangs = new HashSet<Dathang>(0);
	private Set<Chitietsp> chitietsps = new HashSet<Chitietsp>(0);

	public Users() {
	}

	public Users(String username, String password, String password2, String hoTen, int gioiTinh, double sdtUser1,
			String diaChi, Date thoiGianTao, String role, String status) {
		this.username = username;
		this.password = password;
		this.password2 = password2;
		this.hoTen = hoTen;
		this.gioiTinh = gioiTinh;
		this.sdtUser1 = sdtUser1;
		this.diaChi = diaChi;
		this.thoiGianTao = thoiGianTao;
		this.role = role;
		this.status = status;
	}

	public Users(String username, String password, String password2, String email, String hoTen, int gioiTinh,
			double sdtUser1, Double sdtUser2, String diaChi, Date thoiGianTao, Date thoiGianSua, Date thoiGianXoa,
			String role, String status, String moTaThem, Set<Dathang> dathangs, Set<Chitietsp> chitietsps) {
		this.username = username;
		this.password = password;
		this.password2 = password2;
		this.email = email;
		this.hoTen = hoTen;
		this.gioiTinh = gioiTinh;
		this.sdtUser1 = sdtUser1;
		this.sdtUser2 = sdtUser2;
		this.diaChi = diaChi;
		this.thoiGianTao = thoiGianTao;
		this.thoiGianSua = thoiGianSua;
		this.thoiGianXoa = thoiGianXoa;
		this.role = role;
		this.status = status;
		this.moTaThem = moTaThem;
		this.dathangs = dathangs;
		this.chitietsps = chitietsps;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "IdUsername", unique = true, nullable = false)
	public Integer getIdUsername() {
		return this.idUsername;
	}

	public void setIdUsername(Integer idUsername) {
		this.idUsername = idUsername;
	}

	@Column(name = "Username", unique = true, nullable = false)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "Password", nullable = false)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "Password2", nullable = false)
	public String getPassword2() {
		return this.password2;
	}

	public void setPassword2(String password2) {
		this.password2 = password2;
	}

	@Column(name = "Email")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "HoTen", nullable = false)
	public String getHoTen() {
		return this.hoTen;
	}

	public void setHoTen(String hoTen) {
		this.hoTen = hoTen;
	}

	@Column(name = "GioiTinh", nullable = false)
	public int getGioiTinh() {
		return this.gioiTinh;
	}

	public void setGioiTinh(int gioiTinh) {
		this.gioiTinh = gioiTinh;
	}

	@Column(name = "SdtUser1", nullable = false, precision = 22, scale = 0)
	public double getSdtUser1() {
		return this.sdtUser1;
	}

	public void setSdtUser1(double sdtUser1) {
		this.sdtUser1 = sdtUser1;
	}

	@Column(name = "SdtUser2", precision = 22, scale = 0)
	public Double getSdtUser2() {
		return this.sdtUser2;
	}

	public void setSdtUser2(Double sdtUser2) {
		this.sdtUser2 = sdtUser2;
	}

	@Column(name = "DiaChi", nullable = false)
	public String getDiaChi() {
		return this.diaChi;
	}

	public void setDiaChi(String diaChi) {
		this.diaChi = diaChi;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ThoiGianTao", nullable = false, length = 19)
	public Date getThoiGianTao() {
		return this.thoiGianTao;
	}

	public void setThoiGianTao(Date thoiGianTao) {
		this.thoiGianTao = thoiGianTao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ThoiGianSua", length = 19)
	public Date getThoiGianSua() {
		return this.thoiGianSua;
	}

	public void setThoiGianSua(Date thoiGianSua) {
		this.thoiGianSua = thoiGianSua;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ThoiGianXoa", length = 19)
	public Date getThoiGianXoa() {
		return this.thoiGianXoa;
	}

	public void setThoiGianXoa(Date thoiGianXoa) {
		this.thoiGianXoa = thoiGianXoa;
	}

	@Column(name = "Role", nullable = false)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	@Column(name = "Status", nullable = false)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "MoTaThem")
	public String getMoTaThem() {
		return this.moTaThem;
	}

	public void setMoTaThem(String moTaThem) {
		this.moTaThem = moTaThem;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users",cascade = CascadeType.ALL)
	public Set<Dathang> getDathangs() {
		return this.dathangs;
	}

	public void setDathangs(Set<Dathang> dathangs) {
		this.dathangs = dathangs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users",cascade = CascadeType.ALL)
	public Set<Chitietsp> getChitietsps() {
		return this.chitietsps;
	}

	public void setChitietsps(Set<Chitietsp> chitietsps) {
		this.chitietsps = chitietsps;
	}

}
